### ISSUE TITLE
capture.sh: 5: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by alfa07** [shivamashtikar/tmuxjump.vim#4]
On Ubuntu 20.04 I am getting the above error, changing 'sh' to 'bash' in the `system` call fixes it.
https://github.com/shivamashtikar/tmuxjump.vim/blob/main/plugin/tmuxjump.vim#L31

**Comment by shivamashtikar** [comment]
@alfa07 I have fixed the script, updating plugin should work fine now 
Thanks for reporting the issue
